### ISSUE TITLE
Bug Report: [note corntrol things dont work]

### ISSUE THREAD

**Issue by reshggswhthw** [thepercentageguy/Unnamed-FNF-Engine#4] opened 2021-08-21 15:44 UTC

**Comment by thepercentageguy** [comment] 2021-08-22 10:31
can you please explain in more detail what the issue is and how to reproduce it?

**Comment by thepercentageguy** [comment] 2021-08-23 14:08
please respond or i will have to close this issue

**Closed** 2021-08-24 15:15 UTC
Labels: bug
